title: Dog Allergy Check
description: "Science-based information to help you understand and manage your dog's allergies. Expert insights, research, and practical advice for pet owners."
author:
  name: Dog Allergy Check Team
  email: 'info@dogallergycheck.com'
  url: 'https://www.dogallergycheck.com'
  gravatar: info@dogallergycheck.com
  description: "Expert veterinary insights and research-based information for dog allergy management."
blog:
  route: ''
metadata:
    description: 'Dog Allergy Check - Expert insights on dog allergies, nutrition, and health from veterinary professionals and researchers.'
taxonomies: [category,tag,month]

# Show calendar in sidebar
calendar: true 

menu:
  - url: error
    text: Error Page

# Copyright
copyright:
  left: <span>Copyright</span> © {{ "now"|date("Y") }} <a href="https://www.dogallergycheck.com" title="Dog Allergy Check">Dog Allergy Check</a>
  right: <span>Powered by <a href="https://getgrav.org" rel="dofollow" target="_blank" title="Grav">Grav</a> — </span><a title="To the top" class="tothetop">Up ↑</a>
